
using Newtonsoft.Json;

namespace Glitch9.AIDevKit.OpenAI
{
    /// <summary>
    /// Represents the Url or the content of an image generated by the OpenAI API.
    /// </summary>
    public class Image : ModelResponse
    {
        /// <summary>
        /// The base64-encoded JSON of the generated image, if response_format is Base64Json.
        /// </summary>
        [JsonProperty("b64_json")] public string B64Json { get; set; }

        /// <summary>
        /// The URL of the generated image, if response_format is Url (default).
        /// </summary>
        [JsonProperty("url")] public string Url { get; set; }

        /// <summary>
        /// The prompt that was used to generate the image, if there was any revision to the prompt.
        /// </summary>
        [JsonProperty("revised_prompt")] public string RevisedPrompt { get; set; }

    }
}