
using System.Collections.Generic;

namespace Glitch9.AIDevKit.Editor.Pro
{
    /// <summary>
    /// Hard-coded data for model capabilities.
    /// </summary>
    internal static class ModelCapabilityMeta
    {
        internal static Dictionary<string, ModelCapability> Map = new() {
            { "01-ai/yi-large", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming },
            { "aetherwing/mn-starcannon-12b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming },
            { "ai21/jamba-1.5-large", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "ai21/jamba-1.5-mini", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "ai21/jamba-1.6-large", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "ai21/jamba-1.6-mini", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "ai21/jamba-instruct", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "alfredbros/codellama-7b-instruct-solidity", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "allenai/molmo-7b-d:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "all-hands/openhands-lm-32b-v0.1", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "alpindale/goliath-120b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "anthracite-org/magnum-v2-72b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "anthropic/claude-2", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "anthropic/claude-2.0", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "anthropic/claude-2.0:beta", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "anthropic/claude-2.1", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "anthropic/claude-2.1:beta", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "anthropic/claude-3-haiku", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "anthropic/claude-3-haiku:beta", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "anthropic/claude-3-opus", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "anthropic/claude-3-opus:beta", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "anthropic/claude-3-sonnet", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "anthropic/claude-3-sonnet:beta", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "anthropic/claude-3.5-haiku", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "anthropic/claude-3.5-haiku:20241022", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "anthropic/claude-3.5-haiku:beta", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "anthropic/claude-3.5-sonnet-20240620", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "anthropic/claude-3.5-sonnet-20240620:beta", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "anthropic/claude-3.7", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "anthropic/claude-3.7-sonnet", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "anthropic/claude-3.7-sonnet:beta", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "anthropic/claude-3.7-sonnet:thinking", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "agentica-org/deepcoder-14b-preview:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "cohere/command", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "cohere/command-r", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "cohere/command-r-03-2024", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "cohere/command-r-08-2024", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "cohere/command-r7b-12-2024", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "cohere/command-r-plus", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "cohere/command-r-plus-04-2024", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "cognitivecomputations/dolphin-mixtral-8x22b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "cognitivecomputations/dolphin3.0-r1-mistral-24b-instruct", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "cognitivecomputations/dolphin3.0-r1-mistral-24b:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "deepset/deepseek-chat-v3-0324", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "deepset/deepseek-chat-v3-0324:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "deepset/deepseek-prover-v2", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "deepset/deepseek-prover-v2:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "deepset/deepseek-r1-distill-llama-70b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "deepset/deepseek-r1-distill-llama-70b:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "deepset/deepseek-r1-distill-llama-8b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "deepset/deepseek-r1-distill-qwen-14b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "deepset/deepseek-r1-distill-qwen-14b:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "deepset/deepseek-r1-distill-qwen-32b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "deepset/deepseek-r1-distill-qwen-32b:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "deepset/deepseek-r1-zero:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "deepset/deepseek-r1", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "deepset/deepseek-v3-base:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "eleutherai/llemma_7b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "eva-unit-01/eva-llama-3.33-70b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "eva-unit-01/eva-qwen-2.5-72b", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "featherless/qwerky-72b:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "google/gemini-2.0-flash-001", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/gemini-2.0-flash-exp:free", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/gemini-2.0-flash-lite-001", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/gemini-2.5-flash-preview", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/gemini-2.5-flash-preview:thinking", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/gemini-2.5-pro-preview-03-25", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/gemini-3-12b-it", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/gemini-3-12b-it:free", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/gemini-3-1b-it", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/gemini-3-1b-it:free", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/gemini-3-27b-it", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/gemini-3-27b-it:free", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/gemini-flash-1.5", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/gemini-flash-1.5-8b", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/gemini-flash-1.5-8b-exp", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/gemini-pro-1.5", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/gemini-pro-vision", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/gemma-2-27b-it", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/gemma-2-27b-it:free", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/gemma-2-9b-it", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/gemma-2-9b-it:free", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/gemma-3-12b-it", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/gemma-3-12b-it:free", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/gemma-3-1b-it", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/gemma-3-1b-it:free", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/gemma-3-27b-it", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/gemma-3-27b-it:free", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/learnlm-1.5-pro-experimental:free", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/palm-2-chat-bison", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/palm-2-chat-bison-32k", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/palm-2-codechat-bison", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "google/palm-2-codechat-bison-32k", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "huggingfaceh4/zephyr-7b-beta:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "inflection/inflection-3-pi", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "inflection/inflection-3-productivity", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "latitudegames/wayfarer-large-70b-llama-3.3", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "liquid/lfm-3b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "liquid/lfm-40b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "liquid/lfm-7b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "mancer/weaver", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "meta-llama/llama-2-70b-chat", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "meta-llama/llama-3.1-405b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "meta-llama/llama-3.1-405b-instruct", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "meta-llama/llama-3.1-405b:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "meta-llama/llama-3.1-70b-instruct", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "meta-llama/llama-3.1-8b-instruct", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "meta-llama/llama-3.1-8b-instruct:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "meta-llama/llama-3.3-70b-instruct", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "meta-llama/llama-3.3-70b-instruct:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "meta-llama/llama-3.2-11b-vision-instruct", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "meta-llama/llama-3.2-11b-vision-instruct:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "meta-llama/llama-3.2-1b-instruct", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "meta-llama/llama-3.2-1b-instruct:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "meta-llama/llama-3.2-3b-instruct", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "meta-llama/llama-3.2-3b-instruct:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "meta-llama/llama-3.2-90b-vision-instruct", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "meta-llama/llama-3.2-90b-vision-instruct:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "meta-llama/llama-4-maverick", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "meta-llama/llama-4-maverick:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "meta-llama/llama-4-scout", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "meta-llama/llama-4-scout:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "meta-llama/llama-guard-3-8b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "meta-llama/llama-guard-4-12b", ModelCapability.FineTuning },
            { "microsoft/mai-ds-r1:free", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "microsoft/phi-3.5-mini-128k-instruct", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "microsoft/phi-4", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "microsoft/phi-4-multimodal-instruct", ModelCapability.TextGeneration | ModelCapability.Streaming | ModelCapability.SpeechRecognition},
            { "microsoft/wizardlm-2-8x22b", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "minimax/minimax-01", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "mistral/ministral-8b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "mistralai/codestral-2501", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "mistralai/codestral-mamba", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "mistralai/ministral-3b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "mistralai/mistral-3b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "mistralai/mistral-7b-instruct", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "mistralai/mistral-7b-instruct-v0.1", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "mistralai/mistral-7b-instruct-v0.2", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "mistralai/mistral-7b-instruct-v0.3", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "mistralai/mistral-7b-instruct:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "mistralai/mistral-8b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "mistralai/mistral-large-2407", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "mistralai/mistral-large-2411", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "mistralai/mistral-medium", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "mistralai/mistral-nemo", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "mistralai/mistral-nemo:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "mistralai/mistral-saba", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "mistralai/mistral-small", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "mistralai/mistral-small-24b-instruct-2501", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "mistralai/mistral-small-24b-instruct-2501:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "mistralai/mistral-small-3.1-24b-instruct", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "mistralai/mistral-small-3.1-24b-instruct:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "mistralai/mistral-tiny", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "mistralai/pixtral-12b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "mistralai/pixtral-large-2411", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "moonshotai/kimi-vl-a3b-thinking:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "moonshotai/moonlight-16b-a3b-instruct:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "neversleep/llama-3.1-lumimaid-8b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "nothingisreal/mn-celeste-12b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "nousresearch/deephermes-3-llama-3.1-8b-preview", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "nousresearch/hermes-2-pro-llama-3-8b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "nousresearch/hermes-3-llama-3.1-405b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "nousresearch/hermes-3-llama-3.1-70b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "nousresearch/nous-hermes-2-mixtral-8x7b-dpo", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "nvidia/llama-3.1-nemotron-70b-instruct", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "nvidia/llama-3.1-nemotron-ultra-253b-v1:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "nvidia/llama-3.3-nemotron-super-49b-v1", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "nvidia/llama-3.3-nemotron-super-49b-v1:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "open-r1/olympiccoder-32b:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "openai/chatgpt-4o-latest", ModelCapability.TextGeneration | ModelCapability.Streaming | ModelCapability.FunctionCalling},
            { "openai/gpt-3.5-turbo", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming | ModelCapability.FunctionCalling},
            { "openai/gpt-3.5-turbo-0125", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "openai/gpt-3.5-turbo-1106", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming | ModelCapability.FunctionCalling},
            { "openai/gpt-3.5-turbo-16k", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming | ModelCapability.FunctionCalling},
            { "openai/gpt-3.5-turbo-instruct", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "openai/gpt-4", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming | ModelCapability.FunctionCalling},
            { "openai/gpt-4-0314", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "openai/gpt-4-1106-preview", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming | ModelCapability.FunctionCalling},
            { "openai/gpt-4-32k", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming | ModelCapability.FunctionCalling},
            { "openai/gpt-4-32k-0314", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "openai/gpt-4-turbo", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming | ModelCapability.FunctionCalling},
            { "openai/gpt-4-turbo-preview", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming | ModelCapability.FunctionCalling},
            { "openai/gpt-4.1", ModelCapability.TextGeneration | ModelCapability.Streaming | ModelCapability.FunctionCalling},
            { "openai/gpt-4.1-mini", ModelCapability.TextGeneration | ModelCapability.Streaming | ModelCapability.FunctionCalling},
            { "openai/gpt-4.1-nano", ModelCapability.TextGeneration | ModelCapability.Streaming | ModelCapability.FunctionCalling},
            { "openai/gpt-4.5-preview", ModelCapability.TextGeneration | ModelCapability.Streaming | ModelCapability.FunctionCalling},
            { "openai/gpt-4o", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming | ModelCapability.FunctionCalling},
            { "openai/gpt-4o-2024-08-06", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming | ModelCapability.FunctionCalling},
            { "openai/gpt-4o-2024-11-20", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "openai/gpt-4o-mini", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming | ModelCapability.FunctionCalling},
            { "openai/gpt-4o-mini-2024-07-18", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming | ModelCapability.FunctionCalling},
            { "openai/gpt-4o-search-preview", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming | ModelCapability.FunctionCalling | ModelCapability.Search},
            { "openai/o1", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "openai/o1-preview", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "openai/o1-preview-2024-09-12", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "openai/o1-pro", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "openai/o3", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "openai/o3-mini-high", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "openai/o4-mini", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "openai/o4-mini-high", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "opengvlab/internvl3-14b:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "opengvlab/internvl3-2b:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "openrouter/auto", ModelCapability.TextGeneration | ModelCapability.Streaming},
            { "perplexity/llama-3.1-sonar-large-128k-online", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming | ModelCapability.Search},
            { "perplexity/llama-3.1-sonar-small-128k-online", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming | ModelCapability.Search},
            { "perplexity/r1-1776", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "perplexity/sonar", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "perplexity/sonar-deep-research", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming | ModelCapability.Search},
            { "perplexity/sonar-pro", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming | ModelCapability.Search},
            { "perplexity/sonar-reasoning", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "perplexity/sonar-reasoning-pro", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming | ModelCapability.Search},
            { "pygmalionai/mythalion-13b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen-2-72b-instruct", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen-2.5-72b-instruct", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen-2.5-72b-instruct:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen-2.5-7b-instruct", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen-2.5-7b-instruct:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen-2.5-vl-72b-instruct", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen-2.5-vl-72b-instruct:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen-2.5-vl-7b-instruct", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen-2.5-vl-7b-instruct:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen-turbo", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen-vl-max", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen-vl-plus", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen2.5-coder-7b-instruct", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen2.5-vl-32b-instruct", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen2.5-vl-32b-instruct:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen3-0.6b-04-28:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen3-1.7b:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen3-14b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen3-14b:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen3-235b-a22b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen3-235b-a22b:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen3-30b-a3b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen3-30b-a3b:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen3-32b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen3-32b:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen3-4b:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen3-8b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwen3-8b:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwq-32b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwq-32b-preview", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "qwen/qwq-32b:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "rekai/reka-flash-3:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "sao10k/l3-euryale-70b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "sao10k/l3-lunaris-8b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "sao10k/l3.3-euryale-70b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "scb10x/llama3.1-typhoon2-70b-instruct", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "scb10x/llama3.1-typhoon2-8b-instruct", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "shisa-ai/shisa-v2-llama3.3-70b:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "sophosympatheia/midnight-rose-70b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "steelskull/l3.3-electra-r1-70b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "thedrummer/anubis-pro-105b-v1", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "thedrummer/rocinante-12b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "thedrummer/skyfall-36b-v2", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "thudm/glm-4-32b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "thudm/glm-4-32b:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "thudm/glm-z1-32b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "thudm/glm-z1-32b:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "thudm/glm-z1-9b:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "thudm/glm-z1-rumination-32b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "tngtech/deepseek-r1t-chimera:free", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "undi95/remm-slerp-l2-13b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "undi95/toppy-m-7b", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "x-ai/grok-2-1212", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "x-ai/grok-2-vision-1212", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "x-ai/grok-3-beta", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "x-ai/grok-3-mini-beta", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming},
            { "x-ai/grok-beta", ModelCapability.TextGeneration | ModelCapability.FineTuning | ModelCapability.Streaming}
        };
    }
}