using Glitch9.IO.RESTApi;
using Newtonsoft.Json;

namespace Glitch9.AIDevKit
{
    public class ChatChoice
    {
        /// <summary>
        /// The index of the choice in the list of choices.
        /// </summary>
        [JsonProperty("index")] public int Index { get; set; }

        /// <summary>
        /// A chat completion message generated by the model.
        /// </summary>
        [JsonProperty("message")] public ChatMessage Message { get; set; }

        /// <summary>
        /// A streaming chat completion message generated by the model.
        /// </summary>
        [JsonProperty("delta")] public ChatDelta Delta { get; set; }

        /// <summary>
        /// Only used for legacy model requests.
        /// </summary>
        [JsonProperty("text")] public string Text { get; set; }

        /// <summary>
        /// Log probability information for the choice.
        /// </summary>
        [JsonProperty("logprobs")] public Logprobs Logprobs { get; set; }

        /// <summary>
        /// The reason the model stopped generating tokens. 
        /// This will be stopped if the model hit a natural stop point or a provided stop sequence, 
        /// length if the maximum number of tokens specified in the request was reached, 
        /// content_filter if content was omitted due to a flag from our content filters, 
        /// or function_call if the model called a Function.
        /// </summary>
        [JsonProperty("finish_reason")] public string FinishReason { get; set; }
    }

    public class ChatDelta : IChunk
    {
        public static implicit operator string(ChatDelta delta) => delta?.Content ?? string.Empty;

        /// <summary>
        /// The contents of the chunk message.
        /// </summary>
        [JsonProperty("content")] public string Content { get; set; }

        /// <summary>
        /// The refusal message generated by the model.
        /// </summary>
        [JsonProperty("refusal")] public string Refusal { get; set; }

        /// <summary>
        /// The role of the author of this message.
        /// </summary>
        [JsonProperty("role")] public ChatRole Role { get; set; }

        /// <summary>
        /// The name and arguments of a function that should be called, as generated by the model.
        /// /// </summary>
        [JsonProperty("tool_calls")] public ToolCall[] ToolCalls { get; set; }

        public string ToTextDelta() => Content;
    }

    /// <summary>
    /// Log probability information for the choice.
    /// </summary>
    public class Logprobs
    {
        /// <summary>
        /// A list of message content tokens with log probability information.
        /// </summary>
        [JsonProperty("content")] public LogprobsContent[] Content { get; set; }

        /// <summary>
        /// A list of message refusal tokens with log probability information.
        /// </summary>
        [JsonProperty("refusal")] public LogprobsContent[] Refusal { get; set; }
    }

    /// <summary>
    /// A list of message content tokens with log probability information.
    /// </summary>
    public class LogprobsContent
    {
        /// <summary>
        /// The token.
        /// </summary>
        [JsonProperty("token")] public string Token { get; set; }

        /// <summary>
        /// The log probability of this token, if it is within the top 20 most likely tokens.
        /// Otherwise, the value -9999.0 is used to signify that the token is very unlikely.
        /// </summary>
        [JsonProperty("logprob")] public double? Logprob { get; set; }

        /// <summary>
        /// A list of integers representing the UTF-8 bytes representation of the token.
        /// Useful in instances where characters are represented by multiple tokens
        /// and their byte representations must be combined to generate the correct text representation.
        /// Can be null if there is no bytes representation for the token.
        /// </summary>
        [JsonProperty("bytes")] public int[] Bytes { get; set; }

        /// <summary>
        /// List of the most likely tokens and their log probability, at this token position.
        /// In rare cases, there may be fewer than the number of requested top_logprobs returned.
        /// </summary>
        [JsonProperty("top_logprobs")] public LogprobsContent[] TopLogprobs { get; set; }
    }
}
