using Glitch9.EditorKit;
using Glitch9.Internal;
using Glitch9.IO.RESTApi;
using Glitch9.ScriptableObjects;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

namespace Glitch9.AIDevKit.Editor
{
    internal class AIDevKitSettingsProvider : ExtendedSettingsProvider<AIDevKitSettingsProvider, AIDevKitSettings>
    {
        private static readonly string kDefaultRuntimePath = Path.Combine(Application.persistentDataPath, "Generated");
        private static readonly string kDefaultEditorPath = Path.Combine(Application.dataPath, "Generated");

        private static class Labels
        {
            internal static readonly GUIContent EnablePromptHistoryOnRuntime = new("Prompt History On Runtime",
                "If enabled, all generation requests will be saved in your 'PromptHistory.asset' file. If disabled, you need to call '.EnablePromptHistory()' with your GENTask to save the requests.");
            internal static readonly GUIContent RuntimePath = new("Runtime Output Path",
                "The path where the generated files will be saved at runtime. This path must be relative to the persistent data path (Application.persistentDataPath).");
            internal static readonly GUIContent EditorPath = new("Editor Output Path",
                "The path where the generated files will be saved in the editor.");
            internal static readonly GUIContent LogLevel = new("Log Level",
                "The log level determines the verbosity of the logs generated by the AIDevKit. You can choose to log different aspects of the requests and responses.");
        }


        protected static HashSet<string> Keywords { get; } = new()
        {
            "AI",
            "LLM",
            "GenAI",
            "Tools",
            "CodeGen",
        };

        private const int SPACE = 10;
        private const int LABEL_WIDTH = 240;


        [SettingsProvider]
        public static SettingsProvider CreateSettingsProvider()
        {
            AIDevKitSettingsProvider provider = new(AIDevKitEditorConfig.kProviderSettingsCore, SettingsScope.User)
            {
                deactivateHandler = DeactivateHandler,
                keywords = Keywords
            };
            return provider;
        }

        private static void DeactivateHandler()
        {
            AIDevKitSettings.Instance.Save();
        }

        // Settings Properties ---------------------------------------------------------------
        private SerializedProperty defaultLLM;
        private SerializedProperty defaultIMG;
        private SerializedProperty defaultTTS;
        private SerializedProperty defaultSTT;
        private SerializedProperty defaultEMB;
        private SerializedProperty defaultMOD;
        private SerializedProperty runtimeOutputPath;
        private SerializedProperty editorOutputPath;
        private SerializedProperty componentGenerator;
        private SerializedProperty scriptDebugger;
        private SerializedProperty logLevel;
        private SerializedProperty requestTimeout;
        private SerializedProperty promptHistoryOnRuntime;

        // Project Context -------------------------------------------------------------------
        private SerializedProperty projectContext;
        private SerializedProperty defaultPlatform;
        private SerializedProperty tone;
        private SerializedProperty isGame;
        private SerializedProperty appCategory;
        private SerializedProperty gameGenre;
        private SerializedProperty gameTheme;
        private SerializedProperty description;

        // Local Variables ---------------------------------------------------------------
        private readonly EPrefs<int> _savedLogLevel = new("AIDevKit.LogLevel", (int)RESTLogLevel.RequestEndpoint);


        public AIDevKitSettingsProvider(string path, SettingsScope scope = SettingsScope.User) : base(path, scope) { }

        protected override void InitializeSettings()
        {
            // Load the settings properties
            defaultLLM = serializedObject.FindProperty(nameof(defaultLLM));
            defaultIMG = serializedObject.FindProperty(nameof(defaultIMG));
            defaultTTS = serializedObject.FindProperty(nameof(defaultTTS));
            defaultSTT = serializedObject.FindProperty(nameof(defaultSTT));
            defaultEMB = serializedObject.FindProperty(nameof(defaultEMB));
            defaultMOD = serializedObject.FindProperty(nameof(defaultMOD));

            runtimeOutputPath = serializedObject.FindProperty(nameof(runtimeOutputPath));
            editorOutputPath = serializedObject.FindProperty(nameof(editorOutputPath));
            componentGenerator = serializedObject.FindProperty(nameof(componentGenerator));
            scriptDebugger = serializedObject.FindProperty(nameof(scriptDebugger));
            logLevel = serializedObject.FindProperty(nameof(logLevel));
            requestTimeout = serializedObject.FindProperty(nameof(requestTimeout));
            promptHistoryOnRuntime = serializedObject.FindProperty(nameof(promptHistoryOnRuntime));

            projectContext = serializedObject.FindProperty(nameof(projectContext));

            defaultPlatform = projectContext.FindPropertyRelative(nameof(defaultPlatform));
            tone = projectContext.FindPropertyRelative(nameof(tone));
            isGame = projectContext.FindPropertyRelative(nameof(isGame));
            appCategory = projectContext.FindPropertyRelative(nameof(appCategory));
            gameGenre = projectContext.FindPropertyRelative(nameof(gameGenre));
            gameTheme = projectContext.FindPropertyRelative(nameof(gameTheme));
            description = projectContext.FindPropertyRelative(nameof(description));

#pragma warning disable CS0162 // Unreachable code detected
            if (!AIDevKitConfig.IsPro)
            {
                componentGenerator.boolValue = false;
                scriptDebugger.boolValue = false;
            }
#pragma warning restore CS0162 // Unreachable code detected
        }

        protected override void DrawSettings()
        {
            EditorGUIUtility.labelWidth = LABEL_WIDTH;

            DrawDefaultModelApis();

            GUILayout.Space(SPACE);

            DrawGeneralSettings();

            GUILayout.Space(SPACE);

            DrawGenerationSettings();

            GUILayout.Space(SPACE);

            DrawProjectContext();

            GUILayout.Space(SPACE);

            DrawDescription();

            GUILayout.Space(SPACE);

            ExGUILayout.DrawTroubleShootings(AIDevKitEditorConfig.kOnlineDocUrl, EditorConfig.kGithubSupportUrl);

            EditorGUIUtility.labelWidth = 0;
        }

        private void DrawDefaultModelApis()
        {
            ExGUILayout.BeginSection(GUIContents.DefaultModelsSectionTitle);
            {
                AIDevKitGUI.LLMPopup(defaultLLM, AIProvider.All, GUIContents.DefaultLLM);
                AIDevKitGUI.IMGPopup(defaultIMG, AIProvider.All, GUIContents.DefaultIMG);
                AIDevKitGUI.TTSPopup(defaultTTS, AIProvider.All, GUIContents.DefaultTTS);
                AIDevKitGUI.STTPopup(defaultSTT, AIProvider.All, GUIContents.DefaultSTT);
                AIDevKitGUI.EMBPopup(defaultEMB, AIProvider.All, GUIContents.DefaultEMB);
                AIDevKitGUI.MODPopup(defaultMOD, AIProvider.All, GUIContents.DefaultMOD);
            }
            ExGUILayout.EndSection();
        }

        private void DrawGeneralSettings()
        {
            ExGUILayout.BeginSection("General Settings");
            {
                EditorGUILayout.PropertyField(requestTimeout, new GUIContent("Request Timeout", "The timeout for the requests in seconds."));

                EditorGUI.BeginDisabledGroup(AIDevKitDebug.kDebugMode.Value);
                {
                    EditorGUILayout.PropertyField(logLevel, Labels.LogLevel);
                }
                EditorGUI.EndDisabledGroup();

                bool newDebugMode = EditorGUILayout.Toggle("Debug Mode", AIDevKitDebug.kDebugMode.Value);

                if (newDebugMode != AIDevKitDebug.kDebugMode.Value)
                {
                    AIDevKitDebug.kDebugMode.Value = newDebugMode;

                    if (newDebugMode)
                    {
                        AIDevKitDebug.kDebugMode.Value = true;
                        _savedLogLevel.Value = logLevel.intValue;
                        _savedLogLevel.Save();
                        logLevel.intValue = (int)RESTLogLevel.All;
                        logLevel.serializedObject.ApplyModifiedProperties();
                    }
                    else
                    {
                        AIDevKitDebug.kDebugMode.Value = false;
                        logLevel.intValue = _savedLogLevel.Value;
                        logLevel.serializedObject.ApplyModifiedProperties();
                    }
                }
            }
            ExGUILayout.EndSection();
        }

        private void DrawGenerationSettings()
        {
            ExGUILayout.BeginSection("Generation Settings");
            {
                EditorGUILayout.PropertyField(promptHistoryOnRuntime, Labels.EnablePromptHistoryOnRuntime);

                string runtimePath = ExGUILayout.PathField(Labels.RuntimePath, runtimeOutputPath.stringValue, Application.persistentDataPath, kDefaultRuntimePath);
                string editorPath = ExGUILayout.PathField(Labels.EditorPath, editorOutputPath.stringValue, Application.dataPath, kDefaultEditorPath);

                EditorGUI.BeginDisabledGroup(!AIDevKitConfig.IsPro);
                {
                    EditorGUILayout.PropertyField(componentGenerator, new GUIContent("Component Generator (Pro Only)",
                        "The Component Generator adds a 'Generate Component' button under 'Add Component' in the Inspector window." +
                        "This button will generate a new component script based on your prompt."));

                    EditorGUILayout.PropertyField(scriptDebugger, new GUIContent("Script Debugger (Pro Only)",
                        "The Script Debugger adds a 'Debug Script' button under script preview in the Inspector window." +
                        "This button will generate a new script based on your prompt and debug it."));

                    if (!componentGenerator.boolValue)
                    {
                        EditorGUILayout.HelpBox("The Component Generator is disabled. Enable it to see the 'Generate Component' button in the Inspector window.", MessageType.None);
                    }

                    if (!scriptDebugger.boolValue)
                    {
                        EditorGUILayout.HelpBox("The Script Debugger is disabled. Enable it to see the 'Debug Script' button in the Inspector window.", MessageType.None);
                    }
                }
                EditorGUI.EndDisabledGroup();

                if (runtimePath != runtimeOutputPath.stringValue)
                {
                    // check if the path is relative to the persistent data path
                    if (!Path.IsPathRooted(runtimePath) && !runtimePath.StartsWith(Application.persistentDataPath))
                    {
                        Debug.LogWarning($"The runtime path '{runtimePath}' is not relative to the persistent data path '{Application.persistentDataPath}'. " +
                                         "Please enter a valid path relative to the persistent data path.");
                        runtimeOutputPath.stringValue = kDefaultRuntimePath;
                    }
                    else
                    {
                        runtimeOutputPath.stringValue = runtimePath;
                    }

                    runtimeOutputPath.serializedObject.ApplyModifiedProperties();
                }

                if (editorPath != editorOutputPath.stringValue)
                {
                    editorOutputPath.stringValue = editorPath;
                    editorOutputPath.serializedObject.ApplyModifiedProperties();
                }
            }
            ExGUILayout.EndSection();
        }

        private void DrawProjectContext()
        {
            ExGUILayout.BeginSection("Project Context");
            {
                EditorGUILayout.PropertyField(defaultPlatform, new GUIContent("Default Platform", "The default platform for the project."));
                EditorGUILayout.PropertyField(tone, new GUIContent("Language Tone", "The tone of the language used in the project."));
                EditorGUILayout.PropertyField(isGame, new GUIContent("Is This a Game Project?"));

                if (isGame.boolValue)
                {
                    EditorGUILayout.PropertyField(gameGenre, new GUIContent("Game Genre", "The genre of this game. (e.g., Role-playing, Action, etc.)"));
                    EditorGUILayout.PropertyField(gameTheme, new GUIContent("Game Theme", "The lore setting of the game. (e.g., Medieval, Sci-Fi, etc.)"));
                }
                else
                {
                    EditorGUILayout.PropertyField(appCategory, new GUIContent("App Category", "The category of the app. (e.g., Productivity, Entertainment, etc.)"));
                }
            }
            ExGUILayout.EndSection();
        }

        private void DrawDescription()
        {
            ExGUILayout.BeginSection("Project Description");
            {
                const float height = 80f;

                // draw a big text field for the description
                string newDescription = EditorGUILayout.TextArea(description.stringValue, ExEditorStyles.textField, GUILayout.Height(height));
                if (newDescription != description.stringValue) description.stringValue = newDescription;
            }
            ExGUILayout.EndSection();
        }
    }
}